"""create documents table

Revision ID: 1f5fdccd6783
Revises: 
Create Date: 2026-09-20 21:40:02.165035
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '1f5fdccd6783'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('doc_type', sa.String(length=64), nullable=True),
    sa.Column('current_step', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        'report_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True,
    ),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column(
        'attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False,
    ),
    sa.Column(
        'created_at', sa.DateTime(timezone=True),
        server_default=sa.text('now()'), nullable=False,
    ),
    sa.Column(
        'updated_at', sa.DateTime(timezone=True),
        server_default=sa.text('now()'), nullable=False,
    ),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint(
        "outcome IS NULL OR outcome IN ('COMPLETE','INCOMPLETE','UNSUPPORTED')",
        name='ck_documents_outcome',
    ),
    sa.CheckConstraint('size_bytes > 0', name='ck_documents_size_positive'),
    sa.CheckConstraint(
        "outcome IS NULL OR status = 'COMPLETED'",
        name='ck_documents_outcome_requires_completed',
    ),
    sa.CheckConstraint(
        "status IN ('UPLOADING','QUEUED','PROCESSING','COMPLETED','FAILED','EXPIRED')",
        name='ck_documents_status',
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_documents_created_at', 'documents',
        [sa.literal_column('created_at DESC')], unique=False,
    )
    op.create_index(
        'ix_documents_status_lease', 'documents',
        ['status', 'lease_expires_at'], unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_status_lease', table_name='documents')
    op.drop_index('ix_documents_created_at', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
